[build]
  command = "npm install" # ou o comando que você usa para construir seu projeto
  functions = "functions" # caso tenha funções Netlify
  
[dev]
  command = "node ind.js" # ou o comando para iniciar seu aplicativo localmente

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
